#!/usr/bin/python
# -*- coding:utf-8 -*-
r"""
dump_paths.py

WHY NOT `from DocumentLoader import ...` IN YOUR OWN SCRIPT?
============================================================
常见反模式：嫌 PowerShell 引号转义麻烦 → 写临时 .py → from DocumentLoader import ...
本 SKILL 反模式红线段明令禁止（见 ../SKILL.md §反模式红线）。

本 CLI 解决"PowerShell 路径长/含中文/含空格 → 引号转义麻烦"痛点：
  1. 直接调本 CLI 生成 ps1 变量：
     python scripts/dump_paths.py --project-root "D:\项目文档\..." --format ps1 --output-file D:\paths.ps1
  2. PowerShell 加载：
     . D:\paths.ps1
  3. 用变量直接调其他 CLI（路径已被双引号包裹）：
     python scripts/read_doc.py --file $PLANNING_SHEET_LATEST --sheet 评审计划 --output json

退出码：0 成功 / 1 项目根不存在 / 2 找不到策划表（其他变量仍输出）

------------------------------------------------------------
一键输出项目根的常用路径（策划表/项目目录/邮件/输出/变更记录等），
输出格式为 PowerShell 变量赋值，可直接 . (path.ps1) 加载到当前 shell。
复用 find_planning_sheet.find_planning_sheet 顶层函数，避免重复实现。

Date: 2026-06-11
Author: project-doc-query skill
"""

import sys
from pathlib import Path

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")
if hasattr(sys.stderr, "reconfigure"):
    sys.stderr.reconfigure(encoding="utf-8")

_SKILL_SCRIPTS = Path(__file__).resolve().parent
sys.path.insert(0, str(_SKILL_SCRIPTS))

import argparse
import re

# 复用 find_planning_sheet 的版本号提取与查找函数
from find_planning_sheet import find_planning_sheet, extract_version  # noqa: E402


def extract_project_id(project_root_name: str) -> str:
    """从项目根目录名提取项目编号，如 202410-C0008-... -> 202410-C0008"""
    parts = project_root_name.split("-")
    if len(parts) >= 2 and parts[0][:6].isdigit():
        return f"{parts[0]}-{parts[1]}"
    return project_root_name


def powershell_escape(value: str) -> str:
    """PowerShell 双引号字符串内的转义：
    - 反引号 ` -> ``
    - 双引号 " -> `"
    - 美元符 $ -> `$
    - 末尾不加多余转义
    """
    return value.replace("`", "``").replace('"', '`"').replace("$", "`$")


def build_paths(project_root: Path) -> dict:
    """构造所有常用路径变量。"""
    project_id = extract_project_id(project_root.name)
    work_root = project_root.parent  # 项目根的父目录 = 工作根
    project_dir = work_root / ".project" / project_id  # .project/<项目号>/

    planning_dir = project_root / "01_项目策划"
    review_dir = project_root / "03_技术文档及评审"
    output_dir = project_root / "AIAssistive" / "output" / project_id
    change_log = project_root / "06_变更及暂停" / "变更记录.md"

    paths = {
        "PROJECT_ROOT": str(project_root),
        "WORK_ROOT": str(work_root),
        "PROJECT_ID": project_id,
        "PROJECT_DIR": str(project_dir),
        "PROJECT_LOG": str(project_dir / "project_log.md"),
        "CLARIFICATION_LOG": str(project_dir / "clarification_log.md"),
        "DRAFTS_DIR": str(project_dir / "drafts"),
        "PLANNING_DIR": str(planning_dir),
        "REVIEW_DIR": str(review_dir),
        "EMAIL_DIR": str(planning_dir),
        "OUTPUT_DIR": str(output_dir),
        "CHANGE_LOG": str(change_log),
        "PLANNING_SHEET_LATEST": "",
        "PLANNING_SHEET_OLD": "",
    }

    candidates = find_planning_sheet(project_root, "*策划表V*.xlsm")
    if candidates:
        paths["PLANNING_SHEET_LATEST"] = candidates[0]
        if len(candidates) > 1:
            paths["PLANNING_SHEET_OLD"] = candidates[1]

    return paths, candidates


def render_powershell(paths: dict, project_root: Path) -> str:
    """输出 PowerShell 变量赋值格式。"""
    lines = [
        f"# Generated by dump_paths.py",
        f"# Source: {project_root}",
    ]
    for key, value in paths.items():
        if not value:
            escaped = '""'
        else:
            escaped = '"' + powershell_escape(value) + '"'
        lines.append(f"${key} = {escaped}")
    return "\n".join(lines)


def render_env(paths: dict) -> str:
    """输出 KEY=VALUE 格式（通用 shell / dotenv）。"""
    return "\n".join(f"{k}={v}" for k, v in paths.items() if v)


def render_json(paths: dict) -> str:
    """输出 JSON 格式。"""
    import json
    return json.dumps(paths, ensure_ascii=False, indent=2)


def main() -> int:
    parser = argparse.ArgumentParser(
        description="一键输出项目根常用路径（PowerShell .ps1 格式），解决路径转义麻烦",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=(
            "示例:\n"
            "  python dump_paths.py --project-root \"D:\\项目文档\\202410-C0008-...\" --format ps1 --output-file D:\\paths.ps1\n"
            "  PowerShell> . D:\\paths.ps1\n"
            "  PowerShell> python scripts/manage_project_log.py init --work-root $WORK_ROOT --project-id $PROJECT_ID --project-root $PROJECT_ROOT\n"
            "  PowerShell> python scripts/read_doc.py --file $PLANNING_SHEET_LATEST --sheet 评审计划 --output json\n"
        ),
    )
    parser.add_argument("--project-root", required=True, help="项目根目录绝对路径")
    parser.add_argument("--format", choices=["ps1", "env", "json"], default="ps1",
                        help="输出格式：ps1=PowerShell 变量赋值（推荐） / env=KEY=VALUE / json")
    parser.add_argument("--output-file", default=None, help="写到文件路径（推荐，避免控制台乱码）")
    args = parser.parse_args()

    project_root = Path(args.project_root)
    if not project_root.exists():
        print(f"[ERR] 项目根目录不存在: {project_root}", file=sys.stderr)
        return 1

    paths, candidates = build_paths(project_root)
    if not candidates:
        print(f"[WARN] 在 {project_root / '01_项目策划'} 下未找到策划表（其他变量仍输出）", file=sys.stderr)

    if args.format == "ps1":
        text = render_powershell(paths, project_root)
    elif args.format == "env":
        text = render_env(paths)
    else:
        text = render_json(paths)

    if args.output_file:
        out_path = Path(args.output_file)
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(text, encoding="utf-8")
        print(f"[OK] {len(paths)} 个变量已写入 → {out_path}")
        print(f"     加载方式：. \"{out_path}\"")
    else:
        print(text, flush=True)
        print(f"\n[OK] 共 {len(paths)} 个变量（{args.format}）", file=sys.stderr)

    return 0 if candidates else 2


if __name__ == "__main__":
    sys.exit(main())
